version: 0.0
os: linux

files:
  - source: /
    destination: /tmp/build
file_exists_behavior: OVERWRITE
permissions:
  - object: /tmp/build
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: .deployscripts/codedeploy/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: .deployscripts/codedeploy/codedeploy.sh
      timeout: 300
